name: Python Flask App CI

on:
  push:
    branches:
      - main  # Triggers when you push to the main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Use an Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checks out the repository
      
      - name: Set up Python
        uses: actions/setup-python@v2  # Set up Python
        with:
          python-version: '3.9'  # Specify the version of Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip
          pip install -r requirements.txt  # Install dependencies

      - name: Run tests
        run: |
          pytest  # Run tests with pytest
